version: '3.9'
services:
  acompanhamento_db:
    image: postgres
    restart: always
    container_name: acompanhamento_db
    ports: 
      - "5432:5432" 
    volumes:
      - acompanhamento_pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      PGUSER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - acompanhamento_network
      - broker_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      timeout: 10s
      retries: 3
  acompanhamento_api:
      build: .
      container_name: acompanhamento_api
      ports: 
      - "5000:80"   
      depends_on:
        - acompanhamento_db
        - rabbitmq
      networks:
        - acompanhamento_network
        - broker_network
      environment: 
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        BROKER_HOSTNAME: ${BROKER_HOSTNAME}
        BROKER_PORT: ${BROKER_PORT}
        BROKER_USERNAME: ${BROKER_USERNAME}
        BROKER_PASSWORD: ${BROKER_PASSWORD}
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 30s
        retries: 3    
    ports:
      - "5672:5672"
      - "15672:15672" 
    networks:
      - broker_network    
      
volumes:
  mongoManagement:
  acompanhamento_pgsql:

networks:
  acompanhamento_network:
  broker_network:
    driver: bridge
    name: rabbit_broker_network